[tool.poetry]
name = "make-slice"
version = "0.1.0"
description = ""
authors = ["pl <0x00.pl@gmail.com>"]
readme = "README.md"
package = {include = ["make_slice"]}

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
