name: Deploy gh-pages
on:
  push:
    branches: [master]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with=dev

      - name: Run tests with coverage
        run: >
          poetry run pytest -v 
          --junitxml=docs/reports/pytest/report.xml
          --html=docs/reports/pytest/report.html --self-contained-html 
          --cov=make_slice --cov-report=html:docs/reports/htmlcov --cov-report=xml:docs/reports 
          tests/

      - name: generate coverage badge
        run: |
          poetry run genbadge test -i docs/reports/pytest/report.xml -o docs/reports/tests-badge.svg
          poetry run genbadge coverage -i docs/reports/coverage.xml -o docs/reports/coverage-badge.svg

  deploy-doc:
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install mkdocs mkdocs-material mkdocstrings-python
      - run: pip install .  # 安装本地包，确保文档可以正确引用
      - run: mkdocs gh-deploy --force
