name: Lint and Format

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run Ruff linting
        run: poetry run ruff check .

      - name: Run Ruff formatting check
        run: poetry run ruff format --check .
